# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: nondenBot
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.6
  lambdaHashingVersion: 20201221
  environment:
    CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
    GROUPID: ${{ secrets.LINE_GROUPID }}

functions:
  tokyo-cron:
    handler: handler.tokyo_cron
    events:
    - schedule: cron(0 20 20 1-12/1 ? *)
  year-end:
    handler: handler.year_end
    events:
    - schedule: cron(0 20 20 12 ? *)
  obon:
    handler: handler.obon
    events:
    - schedule: cron(0 20 10 8 ? *)
