service: nondenBot
frameworkVersion: '2'

provider:
  name: aws
  region: ap-northeast-1
  runtime: python3.6
  lambdaHashingVersion: 20201221
  environment:
    CHANNEL_ACCESS_TOKEN: LINE_CHANNEL_ACCESS_TOKEN
    GROUPID: LINE_GROUPID

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  tokyo-cron:
    handler: handler.tokyo_cron
    events:
    - schedule: cron(0 11 20 2-12/2 ? *)
  year-end:
    handler: handler.year_end
    events:
    - schedule: cron(0 11 15 2-12/2 ? *)
  obon:
    handler: handler.obon
    events:
    - schedule: cron(0 11 1 2-12/2 ? *)
