service: nondenBot
frameworkVersion: '2'

provider:
  name: aws
  region: ap-northeast-1
  runtime: python3.6
  lambdaHashingVersion: 20201221
  environment:
    CHANNEL_ACCESS_TOKEN: LINE_CHANNEL_ACCESS_TOKEN
    GROUPID: LINE_GROUPID

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  tokyo-cron:
    handler: handler.tokyo_cron
    events:
    - schedule: cron(0 20 20 1/1 ? *)
  year-end:
    handler: handler.year_end
    events:
    - schedule: cron(0 20 20 12 ? *)
  obon:
    handler: handler.obon
    events:
    - schedule: cron(0 20 10 8 ? *)
