on:
  push:
    branches:
      - main
      
name: Deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: make serverless yml channel
        run: python3 replace.py
        env:
          CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          GROUPID: ${{ secrets.LINE_GROUPID }}

      - uses: actions/setup-node@v2
      - name: npm install
        run: npm install -g serverless
      - name: install  serverless-python-requirements
        run: sls plugin install -n serverless-python-requirements

      - name: requirements install
        run: sh requirements.sh
     
      - name: serverless deploy
        run: sls deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
