name: check
on:
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: make serverless yml channel
        run: python3 replace.py
        env:
          CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          GROUPID: ${{ secrets.LINE_GROUPID }}

      - uses: actions/setup-node@v2
      - name: npm install
        run: npm install -g serverless

      - name: requirements install
        run: sh requirements.sh

      - name: install tox
        run:  |
          python -m pip install --upgrade pip
          pip install tox 

      - name: test
        run: tox .